#!/usr/bin/env bash

# Include bootstrap.

. ~/.bash/bootstrap;

# SVN repo requirements.

. ~/.bash/require-svn-repo;

# Run commands.

svn diff --diff-cmd='colordiff' --extensions='--unified=10' "${@}" | less --RAW-CONTROL-CHARS --chop-long-lines;
