#!/usr/bin/env bash

# Include bootstrap.

. ~/.bash/bootstrap;

# SVN repo requirements.

. ~/.bash/require-svn-repo;

# Collect arguments.

message='';

while [[ $# -gt 0 ]]; do
  case "${1}" in
    -m)
      message="${2:-}"
      shift 2 || shift;
      ;;
    --message=*)
      message="${1#*=}"
      shift;
      ;;
    *)
      echo 'Invalid arguments.'; exit 1;
  esac;
done;

# Validate arguments.

if [[ -z "${message:-}" ]]; then
  echo 'One of -m or --message is required.'; exit 1;
fi;

# Run commands.

svn add . --force;
svn commit --message "${message}";
