#!/usr/bin/env bash

# Include bootstrap.

. ~/.bash/bootstrap;

# Git repo requirements.

. ~/.bash/require-git-repo;

# Collect arguments.

message=''; other_branches='';

while [[ $# -gt 0 ]]; do
  case "${1}" in
    -m)
      message="${2:-}";
      shift 2 || shift;
      ;;
    --message=*)
      message="${1#*=}";
      shift;
      ;;
    --other-branch=*|--other-branches=*)
      other_branches="${1#*=}";
      shift;
      ;;
    *)
      echo 'Invalid arguments.'; exit 1;
  esac;
done;

# Validate arguments.

if [[ -z "${message:-}" ]]; then
  echo 'One of -m or --message is required.'; exit 1;
fi;

other_branches="${other_branches// /}";
start_branch="$(git-current-branch)";

# Run commands.

git add --all && git commit --message="${message}" && git push;

if [[ -n "${other_branches}" ]]; then
  IFS=',' read -r -a _other_branches <<< "${other_branches}";
  for _other_branch in "${_other_branches[@]}"; do
    if [[ "${_other_branch}" != "${start_branch}" ]] && git-branch-exists "${_other_branch}"; then
      git checkout "${_other_branch}" && git merge "${start_branch}" && git push;
		  git checkout "${start_branch}";
    fi;
  done;
fi;
