#!/usr/bin/env bash

# Include bootstrap.

. ~/.bash/bootstrap;

# Git repo requirements.

. ~/.bash/require-git-repo;

# Run commands.

git log --abbrev-commit --pretty=oneline --decorate --graph --all "${@}";
