#!/usr/bin/env bash

# Command utils.

function ::() {
  if [[ "${1:-}" == cd || "${1:-}" == dirs ]]; then
    builtin "${@}";
  else
    command -p "${@}";
  fi;
};

function can-run() {
  command -v "${1}" >/dev/null 2>&1;
};
