#!/usr/bin/env bash

# Compare version strings.

function version-compare() {
  local v1="'${1:-}'";
  local v2="'${2:-}'";
  local op="'${3:-}'";

  if [[ "$(php -r 'echo (int)version_compare('"${v1}"', '"${v2}"', '"${op}"');')" == 1 ]]; then
    return 0;
  else
    return 1;
  fi;
};
