#!/usr/bin/env bash

# Include command utils.

. ~/.bash/funcs/::;

# Brew command.

export PATH=''; # Initialize.
export MANPATH=''; # Initialize.
export NODE_PATH=''; # Initialize.
eval "$(/usr/libexec/path_helper -s)";

:: brew "${@}";
