#!/usr/bin/env bash

# Include command utils.

. ~/.bash/funcs/::;

# Brew command.

export PATH=''; # Reset path.
eval "$(/usr/libexec/path_helper -s)";

PATH=/usr/local/sbin:"${PATH}";
PATH=/usr/local/bin:"${PATH}";

:: brew "${@}";
