#!/usr/bin/env bash

# Include bootstrap.

. ~/.bash/bootstrap;

# Get arguments.

remote_ssh_handle='';
local_dir_dir='';
ask_no_questions='';

while [[ $# -gt 0 ]]; do
  case "${1}" in
    --remote-ssh-handle=*)
      remote_ssh_handle="${1#*=}";
      shift;
      ;;
    --local-root-dir=*)
      local_dir_dir="${1#*=}";
      shift;
      ;;
    --ask-no-questions)
      ask_no_questions='-batch';
      shift;
      ;;
    *)
      echo 'Invalid arguments.'; exit 1;
  esac;
done;

local_unison_dir=~/.unison/"${remote_ssh_handle}";
local_unison_prf="${local_unison_dir}"/"${remote_ssh_handle}".prf;

# Validate arguments.

if [[ -z "${remote_ssh_handle}" || ! -f "${local_unison_prf}" ]]; then
	echo 'Invalid --remote-ssh-handle: '"${remote_ssh_handle}"; exit 1;
elif [[ -z "${local_dir_dir}" || ! -d "${local_dir_dir}" ]]; then
	echo 'Invalid --local-root-dir: '"${local_dir_dir}"; exit 1;
elif [[ -n "$(ls -A "${local_dir_dir}")" ]]; then
	echo '--local-root-dir is not empty: '"${local_dir_dir}"; exit 1;
fi;

# Run commands.

find "${local_unison_dir}" -type f ! -name '*.prf' -delete;
ssh "${remote_ssh_handle}" 'find ~/.unison -type f ! -name '"'"'*.prf'"'"' -delete';

UNISON="${local_unison_dir}" unison "${ask_no_questions}" "${remote_ssh_handle}" || true;
