#!/usr/bin/env bash

# Include bootstrap.

. ~/.bash/bootstrap;

# Get arguments.

remote_ssh_handle='';
ask_no_questions='';

while [[ $# -gt 0 ]]; do
  case "${1}" in
    --remote-ssh-handle=*)
      remote_ssh_handle="${1#*=}";
      shift;
      ;;
    --ask-no-questions)
      ask_no_questions='1';
      shift;
      ;;
    *)
      echo 'Invalid arguments.'; exit 1;
  esac;
done;

local_unison_dir=~/.unison/"${remote_ssh_handle}";
local_unison_prf="${local_unison_dir}"/"${remote_ssh_handle}".prf;

# Validate arguments.

if [[ -z "${remote_ssh_handle}" || ! -f "${local_unison_prf}" ]]; then
	echo 'Invalid --remote-ssh-handle: '"${remote_ssh_handle}"; exit 1;
fi;

# Run commands.

find "${local_unison_dir}" -type f ! -name '*.prf' -delete;
ssh "${remote_ssh_handle}" 'find ~/.unison -type f ! -name '"'"'*.prf'"'"' -delete';

if [[ -n "${ask_no_questions}" ]]; then
  UNISON="${local_unison_dir}" unison -batch "${remote_ssh_handle}" || true;
else
  UNISON="${local_unison_dir}" unison "${remote_ssh_handle}" || true;
fi;
