#!/usr/bin/env bash

# Include bootstrap.

. ~/.bash/bootstrap;

# Get arguments.

remote_ssh_handle='';
ask_no_questions='';

while [[ $# -gt 0 ]]; do
  case "${1}" in
    --remote-ssh-handle=*)
      remote_ssh_handle="${1#*=}";
      shift;
      ;;
    --ask-no-questions)
      ask_no_questions='-batch';
      shift;
      ;;
    *)
      echo 'Invalid arguments.'; exit 1;
  esac;
done;

local_unison_dir=~/.unison/"${remote_ssh_handle}";
local_unison_prf="${local_unison_dir}"/"${remote_ssh_handle}".prf;

# Validate arguments.

if [[ -z "${remote_ssh_handle}" || ! -f "${local_unison_prf}" ]]; then
	echo 'Invalid --remote-ssh-handle: '"${remote_ssh_handle}"; exit 1;
fi;

# Run commands.
UNISON="${local_unison_dir}" unison "${ask_no_questions}" -repeat watch "${remote_ssh_handle}";
